### ISSUE TITLE
cespare/reflex@v0.3.0: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by jaypatelh** [ic3network/mccs-alpha#10]
Hello team! First of all, thank you for building this open source software! I'm very excited to try it out, and am keen on starting a mutual credit network in my community (in Silicon Valley, California, US). I was going through the Getting Started guide, and am running into an issue when running `make run`:

```
Step 7/8 : RUN go get github.com/cespare/reflex
 ---> Running in 3d800a1dc998
go: finding github.com/cespare/reflex v0.3.0
go: downloading github.com/cespare/reflex v0.3.0
verifying github.com/cespare/reflex@v0.3.0: github.com/cespare/reflex@v0.3.0: Get https://sum.golang.org/lookup/github.com/cespare/reflex@v0.3.0: x509: certificate signed by unknown authority
The command '/bin/sh -c go get github.com/cespare/reflex' returned a non-zero code: 1
ERROR: Service 'web' failed to build
make: *** [run] Error 1
```

I googled it and saw some answers that suggested updating the ca-certificates, so I added the following to the `dockerfile.dev`, but it didn't help:

```FROM golang:1.13
  
WORKDIR /usr/src/app

COPY go.mod .
COPY go.sum .

RUN go get -v -t -d ./...

RUN apt-get update \
        && apt-get upgrade -y \
        && apt-get install ca-certificates -y \
        && update-ca-certificates -y

RUN go get github.com/cespare/reflex

CMD ["reflex", "-c", "./reflex.dev.conf"]
```

I'd appreciate any guidance on how to resolve this issue! Thank you so much! Can't wait to get everything running locally. :)

**Comment by geoffturk** [comment]
@jaypatelh I just set up the project from scratch and it installed and loaded fine. It looks like there might have been a TLS (encryption) error in your log above when the installer tried to pull something from GitHub. It might have been a temporary glitch. Can you try erasing all the containers and images and try again?
