### ISSUE TITLE
Incorrect smallcase of email field in Signup page

### ISSUE THREAD

**Issue by glowkeeper** [ic3network/mccs-alpha#7]
This one's a bit random ;)

On the signup page, if you accidentally have caps lock on in the two email fields, but incorrectly fill out the form, the email field will get corrected to smallcase, but the reconfirm email field will be left as CAPS. Consequently, when you try and submit the form, the emails won't match.

**Comment by geoffturk** [comment]
@glowkeeper Nice catch. Please keep this in mind for the React front end.
